[package]
name = "couchapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
futures-util = "0.3.28"
async-trait = "0.1.72"
axum = { version = "0.6.20", features = ["macros", "headers"] }
hyper = "0.14.27"
tower-http = { version = "0.4.3", features = ["trace"] }
reqwest = { version = "0.11.20", features = ["json"] }
walkdir = "2.3.3"
toml = "0.7.4"
boa_engine = "0.17.0"
base64 = "0.21.2"
indexmap = "2.0.0"
url = "2.4.0"
headers = "0.3.8"

# MongoDB
bson = "2.6.1"
mongodb = { version = "2.6.1", features = ["aws-auth"] }

# Generic JSON stuff
serde = "1.0.186"
serde_json = "1.0.105"
serde_derive = "1.0.186"
uuid = "1.4.1"
md5 = "0.7.0"
maplit = "1.0.2"

# Logging
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }

# Configuration
config = "0.13.3"
clap = { version = "4.3.24", features = ["derive"] }

[dev-dependencies]
mockall = "0.11.4"
assert-json-diff = "2.0.2"
httpmock = "0.6.8"
