[package]
name = "couchapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.27.0", features = ["full"] }
futures-util = "0.3.28"
async-trait = "0.1.68"
axum = "0.6.18"
tower-http = { version = "0.4.1", features = ["trace"] }

# MongoDB
bson = "2.6.1"
mongodb = "2.5.0"

# Generic JSON stuff
serde = "1.0.163"
serde_json = "1.0.96"
serde_derive = "1.0.163"
uuid = "1.3.3"
md5 = "0.7.0"

# Logging
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "json"] }

# Configuration
config = "0.13.3"
clap = { version = "4.3.0", features = ["derive"] }

[dev-dependencies]
mockall = "0.11.4"